### ISSUE TITLE
Usage with parcel

### ISSUE THREAD

**Issue by ValeriiMakhniuk** [posthtml/posthtml-css-modules#12]
i am using parcel as bundler in my project:
**My problem:**
`[posthtml-css-modules] CSS module "lol" is not found`
**index.html**
```
...
<body>
    <div css-module="lol">123</div>
  </body>
```
**styles.css**
```
.lol {
  width: 200px;
  height: 200px;
  background-color: red;
}
```
**Configs**
`.posthtmlrc`:
```
{
  "plugins": {
    "posthtml-css-modules": {}
  }
}
```
`.postcssrc`:
```
{
  "modules": true,
}

```

**Comment by maltsev** [comment]
It seems that `parcel` doesn't pass the CSS modules to `posthtml-css-modules`. I never used Parcel, so I'm not familiar with its internal API. It's better if you post this issue to their repo.

Feel free to re-open this issue if it turns out to be a bug in my module.
